name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint & typecheck
        run: |
          ruff check .
          mypy .

      - name: Run tests
        run: pytest --maxfail=1 --disable-warnings -q

      - name: Security scan
        run: |
          bandit -r .
          pip-audit